name: haversine_distance
description: A flutter pacakge to calculate the distance between two coordinates
version: 1.2.0
homepage: https://github.com/ertkjern/flutter_haversine

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dev_dependencies:
  test: ^1.16.6
