name: haversine_distance
description: A flutter pacakge to calculate the distance between two coordinates
version: 1.2.1
homepage: https://github.com/ertkjern/flutter_haversine

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.16.6
